name: qcga-leo-uav
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pip
  - pip:
      - pandas
